name: Deploy ASP.NET Core API via FTP and Send Email Notification

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Coloque a versão do .NET que você está usando

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Publish the project (will generate files in 'publish' directory)
      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish --no-build

      # Install FTP client (to use for FTP transfer)
      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy to FTP using lftp
        run: |
          lftp -e "set ftp:ssl-allow no; set ftp:passive-mode on; mirror -R ./publish /www.hebermattos.somee.com; bye" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST

