name: Deploy ASP.NET Core API via File Copy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: local-example

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # Publish the project (will generate files in 'publish' directory)
      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish --no-build

      # Backup deployment folder
      - name: Backup
        run: cp -r /heber-deploy/* /backup-heber-deploy

      # Copy files to deployment folder
      - name: Copy files to deployment folder
        run: cp -r ./publish/* /heber-deploy


          
